### ISSUE TITLE
K8s: Custom Ingress Controller ~ Metac Idea

### ISSUE THREAD

**Issue by AmitKumarDas** [AmitKumarDas/Decisions#244]
https://www.doxsey.net/blog/how-to-build-a-custom-kubernetes-ingress-controller-in-go

**Comment by AmitKumarDas** [comment]
Kubernetes has support for mapping external domains to internal services via Ingress objects. The Ingress object I'm using looks like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: doxsey-www
spec:
  tls:
    - hosts:
        - "*.doxsey.net"
      secretName: doxsey-net-tls
  rules:
    - host: www.doxsey.net
      http:
        paths:
          - path: /
            backend:
              serviceName: doxsey-www
              servicePort: 9002
```

This manifest declares how incoming HTTP traffic should be routed to backend services:
- Any HTTP request to the www.doxsey.net domain, for any path will be routed to the doxsey-www service.
- If this is an HTTPS request, and the domain matches *.doxsey.net, the doxsey-net-tls certificate will be used for the request.
