### ISSUE TITLE
Rust: Trait extends standard library types

### ISSUE THREAD

**Issue by AmitKumarDas** [AmitKumarDas/Decisions#51]
It is so difficult to accept that adding a dependency in Cargo.toml and subsequently adding the crate & using it `auto-magically` adds new behaviours to existing types.

- Cargo.toml
```toml
[dependencies]
unicode-segmentation = "0.1.2"
```
- lib.rs
```rust
extern crate unicode_segmentation;

use unicode_segmentation::UnicodeSegmentation;
```
